### ISSUE TITLE
Broken taglib.org Website

### ISSUE THREAD

**Issue by rjstelling** [taglib/taglib.github.io#7]
Hi,

http://taglib.github.io is broken (404) and so all our automated build systems that fetch the tar files form: http://taglib.github.io/releases/taglib-X.XX.tar.gz are failing.

We have now moved to: https://github.com/taglib/taglib/releases/tag/vX.XX.

Regards,

Rich

**Comment by ryandesign** [comment]
[MacPorts observed the same thing](https://trac.macports.org/ticket/52712).

I believe you should be able to resolve this issue by renaming the repository back to taglib.github.io.

**Comment by scotchi** [comment]
Ah, interesting.  Incidentally the repository was still named after the old `.com` address, so it wasn't even previous the `.io`, but renaming that, plus the CDN refreshing, seems to have resolved the issue.  Thanks!

**Comment by scotchi** [comment]
Also, probably the links should point to `taglib.org` now, since ideally (and part of the logic behind the switch) was that even if the hosting moves in the future that links won't have to break.
